name: build & deploy performance frontend to s3
on:
  push:
    branches:
      - main
# env:
#   AWS_ASSUME_ROLE : your_oidc_identity_role
#   AWS_REGION : your_region

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.13.1]

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: install node modules
        run: |
          npm ci --prefix client

      - name: build
        run: |
          npm run build --prefix client

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GithubActionsSession
          aws-region: ${{ secrets.AWS_REGION }}
        # with:
        #   role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
        #   role-session-name: GithubActionsSession
        #   aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to AWS S3
        run: |
          aws s3 sync ./client/dist/ s3://performance-frontend/ --delete --metadata "Cache-Control=public, max-age=3600, s-maxage=86400" --exclude "*.map"

      - name: CF cache invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID}} --paths '/*'
